### ISSUE TITLE
Открывать картинки в новом окне по клику

### ISSUE THREAD

**Issue by tonsky** [tonsky/grumpy#10]
Картинки должны стать ссылками, которые открывают сами себя (.jpg/.png) в новом окне

**Comment by dapi** [comment]
Почему в новом？Не приятно когда что-то открывается в новом окне без моего ведома. Если мне надо будет ссылку открыть в новом окне, то я кликну на нее вместе с зажатым альтом.

**Comment by tonsky** [comment]
потому что можно нечаянно жмакнуть по картинке в середине ленты и потом час до этой середины проматывать. Как негативный пример см. web twitter
