### ISSUE TITLE
Не заполняется автор поста

### ISSUE THREAD

**Issue by igrishaev** [tonsky/grumpy#16]
Каким-то образом вот этот пост https://grumpy.website/post/0PISqXJzk опубликовался под анонимом. Внутри edn-файла не было ключа `:author`.

Возможно, это связано с черновиками: сначала я создал этот пост: https://grumpy.website/post/0PISe1tMj Затем открыл форму создания нового, но смутился тем, что в форме уже был контент предыдущего поста. Как я понимаю, туда подставился черновик. Я подумал, что по ошибке правлю старый пост, нажал "назад", потом опять плюсик. Удалил контент из формы, нажал сабмит -- пост создался под анонимом.

Полагаю, нужно как-то следить, что если пост успешно ушел на сервер, то черновик удалять. На сервере всегда проверять, что автор заполнен, потому что аноним не может создать пост сам.

В идеале можно было бы добавить в форму поле "автор" для гостевого или анонимного поста. По умолчанию в нем ник текущего пользователя. Можно вписать иное для гостевого поста. Если пусто, то анонимный.

**Comment by tonsky** [comment]
Пока что can’t reproduce
