### ISSUE TITLE
Картинки сжимаются по ширине

### ISSUE THREAD

**Issue by tonsky** [tonsky/grumpy#17]
Должны всегда сжиматься пропорционально. Засада в том, что у некоторых из них размер известен (и подставляется), а у некоторых нет. В принципе, это может быть два разных решения на эти два случая. Надо CSS кун-фу

**Comment by ermouth** [comment]
Имхо высоту можно вообще не задавать. Или я неправильно проблему понимаю?

**Comment by tonsky** [comment]
наоборот, чтобы при загрузке не прыгало, надо задавать

**Comment by ermouth** [comment]
Тогда придётся разбирать картинки, заодно это решает массовую проблему с неверным Exif-ом картинок с мобил. В браузерной js-вселенной я использую для этого https://github.com/blueimp/JavaScript-Load-Image, наверное на Кложе что-то такое же есть.

**Comment by SelenIT** [comment]
Чтобы при загрузке _адаптивных_ картинок не прыгало, задавать _конкретную_ высоту вроде как бессмысленно, надо задавать _пропорции_? Или я чего-то недопонимаю?

**Comment by tonsky** [comment]
высота известна, надо как-то так с CSS извратиться теперь, чтобы размер/пропорции указать

**Comment by bushyn** [comment]
может они сжимаются от того что ширина явно указывается?

**Comment by tonsky** [comment]
ну убрать `width` вообще или поставить `width: auto` вроде бы не помогает

**Comment by nanot1m** [comment]
Если я правильно понял то тебе интересно свойство `object-fit`
```css
img {
  object-fit: cover;
}
```
[Пример](https://codepen.io/t1mmaas/pen/eyMWJB?editors=0100)

**Comment by bushyn** [comment]
непонятно что надо-то :) 
если просто бесит что непропорционально картинки сжимаются то отсавь в .post_img {  max-width: 100%; } и не добавляй к img width
если надо fill/fit/strech/tile то вон специальное свойство недавно завезли

**Comment by tonsky** [comment]
Вот что я хочу: ширина картинки динамическая от viewport, с max-width 550px; Высота пропорциональна ширине и известна до загрузки картинки (чтобы контент не прыгал). Похоже что придется старый добрый https://stackoverflow.com/questions/1495407/maintain-the-aspect-ratio-of-a-div-with-css юзать

object-fit это не то. Картинка-то фиксится, а поля остаются

Убрать width не помогает (потому что height абсолютный)

**Comment by bushyn** [comment]
в so для div'a описано. для картинок оно само считает же. делай быстрее, мы посмотрим :)

**Comment by ermouth** [comment]
Я наконец-то понял, что ты хочешь ) Проще всего это сделать div-ом, у которого padding-top (или bottom) задан в процентах, а проценты – aspect ratio картинки. То-есть если картинка 1000х600, padding-top:60%. А потом этому div задать бэкграунд из картинки.

**Comment by bushyn** [comment]
"семь красных линий"
