### ISSUE TITLE
Atom feed is broken

### ISSUE THREAD

**Issue by Torvin** [tonsky/grumpy#33]
The feed is broken: https://grumpy.website/feed.xml

What the web site generates:
```xml
<feed xmlns:b="http://www.w3.org/2005/Atom" xml:lang="ru">
```

It really should be `xmlns` instead of `xmlns:b`. Not sure why this happens, the code [seems correct](https://github.com/tonsky/grumpy/blob/master/src/grumpy/feed.clj#L26), but this prevents my RSS client from rendering the feed

**Comment by Torvin** [comment]
The same seems to be happening to `sitemap.xml`: only difference is it contains `xmlns:a`

**Comment by tonsky** [comment]
Thanks @Torvin! Should be fixed by https://github.com/tonsky/grumpy/commit/d388df156eee6425e15ed02bcaba471fd7f62dcd

**Comment by Torvin** [comment]
It works now, thank you. But every `<content>` now includes the post text twice

**Comment by tonsky** [comment]
OMG hopefully fixed now. Thanks again!

**Comment by Torvin** [comment]
Looks perfect now, cheers!
